# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: name

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                provider: user_provider
                login_path: user_login
                check_path: user_check
            logout:
                path: user_logout
    access_control:
               - { path: ^/product , roles: IS_AUTHENTICATED_ANONYMOUSLY }
               - { path: ^/register , roles: IS_AUTHENTICATED_ANONYMOUSLY }
               - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
               - { path: ^/admin, roles: ROLE_ADMIN }
               - { path: ^/, roles: [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN] }
